version: "3"
containers:
- name: workstation
  image: hrushikeshkanade/jetbrains-instruqt:latest
  ports:
  - port: 8080
    path: /vnc_auto.html
  memory: 8192
  cpus: 4
  environment:
    DISPLAY: ":1"
